# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-08 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessages',
            name='message_type',
            field=models.CharField(choices=[('teacher_schedules', "Teacher's Schedules"), ('student_schedules', "Student's Schedules"), ('all_teachers', 'All Teachers'), ('all_students', 'All Students'), ('all_users', 'All Users')], default='teacher_schedules', max_length=300),
        ),
    ]
