# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmessages_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='message_type',
            field=models.CharField(choices=[('teacher_schedules', "Teacher's Schedules"), ('student_schedules', "Student's Schedules"), ('all_teachers', 'All Teachers'), ('all_students', 'All Students'), ('students_low_hours', 'Students Low on Hours'), ('all_users', 'All Users')], default='teacher_schedules', max_length=300),
        ),
    ]
