# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190926_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='message_type',
            field=models.CharField(choices=[('teacher_unconfirmed', 'Teacher Attendance Unconfirmed'), ('student_unconfirmed', 'Student Attendance Unconfirmed'), ('teacher_schedules', "Teacher's Schedules"), ('student_schedules', "Student's Schedules"), ('all_teachers', 'All Teachers'), ('all_students', 'All Students'), ('students_low_hours', 'Students Low on Hours'), ('all_users', 'All Users')], default='teacher_schedules', max_length=300),
        ),
    ]
