# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-07 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_billing', '0002_auto_20191107_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbillingrates',
            name='teacher_billed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
