# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_billing', '0003_auto_20191107_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTotalBillingHours',
            fields=[
                ('teacher_billing_hours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher_billing.TeacherBillingHours')),
                ('total_billed_inside_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_billed_outside_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
