# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-13 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190908_0840'),
        ('teacher_billing', '0006_teachertotalcustombillinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCumulativeCustomBillingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_hours_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_period', to='teacher_billing.TeacherBillingPeriod')),
                ('custom_billing', models.ManyToManyField(blank=True, related_name='custom_billing_accounts', to='teacher_billing.TeacherCustomBillingHours')),
                ('teacher_billed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_billed', to='accounts.Profile')),
            ],
        ),
    ]
