# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-17 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190908_0840'),
        ('teacher_billing', '0007_teachercumulativecustombillinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCumulativeMonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cumulative_payment', models.PositiveIntegerField(default=0)),
                ('paid_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_paid', to='accounts.Profile')),
                ('payment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_period', to='teacher_billing.TeacherBillingPeriod')),
            ],
        ),
    ]
