# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-18 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_billing', '0008_teachercumulativemonthlypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCumulativeCustomBillingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_custom_cumulative_payment', models.PositiveIntegerField(default=0)),
                ('cumulative_custom_billing_hours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_custom_billing', to='teacher_billing.TeacherCumulativeCustomBillingHours')),
            ],
        ),
    ]
