# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('class_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('schedule_time_finish', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('student_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_classes.StudentClass')),
                ('class_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancellation_request', 'Cancellation_Request'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('same_day_cancellation', 'Same_Day_Cancellation')], default='scheduled', max_length=300)),
                ('teacher_attended', models.BooleanField(default=False)),
                ('student_attended', models.BooleanField(default=False)),
                ('class_content', models.TextField(blank=True, default='')),
                ('absence_request_reason', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_locations.ClassLocation')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('student_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_classes.StudentClass')),
                ('hours_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('teacher_scheduled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scheduled', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='studentclass',
            name='student_scheduled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_scheduled', to='accounts.Profile'),
        ),
    ]
