# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='slug',
            field=models.SlugField(default='2019-06-11'),
            preserve_default=False,
        ),
    ]
