# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0002_studentclass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
