# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-14 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_classes', '0003_auto_20190703_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='students_in_attendance',
            field=models.ManyToManyField(blank=True, related_name='students_in_attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
