# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('student_classes', '0004_classinformation_students_in_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='student_scheduled',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='student_scheduled',
            field=models.ManyToManyField(null=True, related_name='student_scheduled', to='accounts.Profile'),
        ),
    ]
