# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0005_auto_20190715_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student_scheduled',
            field=models.ManyToManyField(related_name='student_scheduled', to='accounts.Profile'),
        ),
    ]
