# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-08 08:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0006_auto_20190825_0551'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentclass',
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
