# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0007_auto_20190908_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclass',
            name='teacher_scheduled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scheduled', to='accounts.Profile'),
        ),
    ]
