# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_billing_admin', '0003_studentbilling_slug'),
        ('student_classes', '0008_auto_20191003_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='student_billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_billing_admin.StudentBilling'),
        ),
    ]
