# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_billing', '0003_auto_20191107_0018'),
        ('student_classes', '0009_classinformation_student_billing_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='custom_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_billing.TeacherCustomBillingRates'),
        ),
    ]
