# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('class_billing_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentbilling',
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='studentbilling',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
