# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_billing_admin', '0002_auto_20190922_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbilling',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
